// Bundled rather than tsc output plus node_modules, so the installed plugin
// runs without an install step inside a product repository.
import { build } from 'esbuild';
import { chmod, mkdir, rm, writeFile } from 'node:fs/promises';

await rm(new URL('./scripts/ambicode.mjs', import.meta.url), { force: true });
// A chunk left from an earlier build would otherwise be packaged beside the new ones.
await rm(new URL('./scripts/chunks/', import.meta.url), { recursive: true, force: true });

await build({
  entryPoints: { ambicode: 'src/cli/main.ts', guard: 'src/hook/guard.ts' },
  outdir: 'scripts',
  outExtension: { '.js': '.mjs' },
  // `view` is imported dynamically so its page server (Fastify, Eta) is parsed
  // by `view` alone. Content-hashed names keep two builds byte-identical.
  splitting: true,
  chunkNames: 'chunks/[name]-[hash]',
  bundle: true,
  platform: 'node',
  target: 'node24',
  format: 'esm',
  sourcemap: false,
  legalComments: 'none',
  // `yaml` is CommonJS and calls require('process') at load time; esbuild's ESM
  // require shim refuses builtins, so a real require is supplied for it to find.
  banner: {
    js: [
      '#!/usr/bin/env node',
      "import { createRequire as __ambicodeCreateRequire } from 'node:module';",
      'const require = __ambicodeCreateRequire(import.meta.url);',
    ].join('\n'),
  },
  logLevel: 'info',
});

const binDirectory = new URL('./bin/', import.meta.url);
await mkdir(binDirectory, { recursive: true });
const launcher = new URL('./ambicode', binDirectory);
await writeFile(
  launcher,
  ['#!/bin/sh', '# Generated by build.mjs; edit src/cli/main.ts instead.', 'exec node "$(dirname "$0")/../scripts/ambicode.mjs" "$@"', ''].join('\n'),
);
await chmod(launcher, 0o755);
await writeFile(
  new URL('./ambicode.cmd', binDirectory),
  ['@echo off', 'node "%~dp0..\\scripts\\ambicode.mjs" %*', ''].join('\r\n'),
);
