// Bundles the helper sources into one distributable entry point under scripts/.
// Bundling (rather than shipping tsc output plus node_modules) keeps the
// installed plugin runnable without an install step inside a product repository.
import { build } from 'esbuild';
import { chmod, mkdir, rm, writeFile } from 'node:fs/promises';

await rm(new URL('./scripts/ambicode.mjs', import.meta.url), { force: true });
// A chunk left from an earlier build would otherwise be packaged beside the new ones.
await rm(new URL('./scripts/chunks/', import.meta.url), { recursive: true, force: true });

await build({
  entryPoints: { ambicode: 'src/cli/main.ts' },
  outdir: 'scripts',
  outExtension: { '.js': '.mjs' },
  // `view` is imported dynamically so its page server — Fastify, its plugins
  // and Eta, 1.5 MB of a 3.4 MB bundle — is parsed by `view` alone rather than
  // by every hook, `prepare` and `review`. Content-hashed names keep two builds
  // of the same source byte-identical, which `package:reproducible` checks.
  splitting: true,
  chunkNames: 'chunks/[name]-[hash]',
  bundle: true,
  platform: 'node',
  target: 'node24',
  format: 'esm',
  sourcemap: false,
  legalComments: 'none',
  // `yaml` is CommonJS and calls require('process') at load time; esbuild's ESM
  // require shim refuses builtins, so a real require is supplied for it to find.
  banner: {
    js: [
      '#!/usr/bin/env node',
      "import { createRequire as __ambicodeCreateRequire } from 'node:module';",
      'const require = __ambicodeCreateRequire(import.meta.url);',
    ].join('\n'),
  },
  logLevel: 'info',
});

// Convenience launchers for interactive Bash/PowerShell use. Hooks and skills
// call the bundled Node entry point directly, so correctness never depends on
// PATH injection or on a POSIX shell being present.
const binDirectory = new URL('./bin/', import.meta.url);
await mkdir(binDirectory, { recursive: true });
const launcher = new URL('./ambicode', binDirectory);
await writeFile(
  launcher,
  ['#!/bin/sh', '# Generated by build.mjs; edit src/cli/main.ts instead.', 'exec node "$(dirname "$0")/../scripts/ambicode.mjs" "$@"', ''].join('\n'),
);
await chmod(launcher, 0o755);
await writeFile(
  new URL('./ambicode.cmd', binDirectory),
  ['@echo off', 'node "%~dp0..\\scripts\\ambicode.mjs" %*', ''].join('\r\n'),
);
