import type { ProjectConfig } from '../contracts/config.ts';
import type { LocateCandidate } from '../contracts/locate.ts';
import type { RequirementSource } from '../contracts/requirements.ts';
import { literalPathspec, type Git } from '../git/git.ts';
import { pathExclusionReason } from '../snapshot/exclusions.ts';
import { matchesGlob } from '../util/glob.ts';
import { normalizeRelative } from '../util/paths.ts';

/**
 * The boundary shortlist (R4, core idea #2): the files a request is probably
 * about, ranked, each with the reason it ranked.
 *
 * Every signal below is computed on demand from data git already holds. There
 * is no index, no cache, no symbol table and no dependency graph — those are
 * `plan/09-backlog.md` items and they stay there. The whole of this module's
 * state lives on the stack of one call, which is what keeps it honest: a
 * shortlist that cannot go stale is one nobody has to invalidate.
 *
 * The shortlist is a hypothesis for the caller to confirm, never an answer.
 * It says what it could not establish in `limitations`, and when it finds
 * nothing it returns nothing — it never widens into "here is the whole
 * project", which is the same rule `src/checks/select.ts` applies to test
 * selection.
 */

/** A starting point for an agent, not a context dump. */
export const DEFAULT_LOCATE_LIMIT = 20;

/**
 * Half that inside `prepare`, whose payload is re-sent on every call and
 * whose byte cost R2 measures. Ten candidates are enough to start from; a
 * caller that wants the long list runs `ambicode locate` for it.
 */
export const PREPARE_SHORTLIST_LIMIT = 10;

/** Terms beyond this are dropped: an unbounded term list is an unbounded scan. */
const MAX_TERMS = 12;

/** Shorter than this matches too much of any codebase to mean anything. */
const MIN_TERM_LENGTH = 3;

/** Per term, per signal. A term matching more than this is bounded and said so. */
const MAX_CONTENT_MATCHES_PER_TERM = 200;

/** A few hundred commits: enough for a habit to show, bounded so it stays fast. */
const MAX_COCHANGE_COMMITS = 200;

/** Fewer than this and co-change is coincidence, not habit. */
const MIN_COCHANGE_COMMITS = 2;

/** A path must accompany a seed at least this often before it is worth saying. */
const MIN_COCHANGE_SHARE = 0.25;
const MIN_COCHANGE_COUNT = 2;

/**
 * A sweeping commit — a reformat, a licence header, the initial import — puts
 * every file next to every other one and says nothing about which files form
 * a boundary. It is excluded from co-change, and the exclusion is reported.
 */
const MAX_COCHANGE_COMMIT_FILES = 50;

/**
 * The same objection from the other side. A sweeping commit puts every file
 * next to every other one; a file that moves in lockstep with many others
 * belongs to a set that is maintained as a block — a translation family
 * regenerated by an export, a generated client, a fixture directory. Knowing
 * that one of them moved says nothing about which of them to open, so that
 * seed's companionship is dropped and the shortlist says so.
 *
 * This is what a real ticket hit: eight locale files, each carrying the
 * ticket's own words and each co-changing perfectly with the other seven,
 * filled every slot of the shortlist while the directory actually named for
 * the feature was nowhere in it.
 */
const MAX_COCHANGE_PARTNERS = 6;

/** The already-matched files co-change is measured against. */
const MAX_SEEDS = 5;

/**
 * Scores are comparable within one call and nothing more: they order a list,
 * they do not measure a probability. A directory named for the term is the
 * strongest single signal that a boundary was found, a filename next, and a
 * mention in the contents weakest — a word can appear in any comment.
 */
const SCORE_DIRECTORY = 5;
const SCORE_FILENAME = 3;
const SCORE_CONTENT = 2;
/** Scaled by the share of the seed's commits, so a habit outranks an accident. */
const SCORE_COCHANGE = 4;

/**
 * Mentions have diminishing returns, and however many terms a file mentions
 * they never add up to having the boundary named: the total approaches
 * `2 * SCORE_CONTENT`, which is below `SCORE_DIRECTORY` by construction.
 *
 * Without this, a file that merely says the words wins by saying them often.
 * A ticket's terms overlap heavily — "ORD-17" and "ORD-17-1" are one fact,
 * not two — so a translation file carrying the ticket's prose three times
 * scored 6 and outranked the directory that is actually named for it. Three
 * weak signals are still weak.
 */
function contentScore(hits: number): number {
  return hits <= 0 ? 0 : SCORE_CONTENT * (2 - 2 ** (1 - hits));
}

export interface LocateRequest {
  git: Git;
  project: ProjectConfig;
  terms: readonly string[];
  limit: number;
}

export interface LocateShortlist {
  terms: string[];
  candidates: LocateCandidate[];
  limitations: string[];
}

interface Ranked {
  path: string;
  /** Path and co-change score, which accumulate without a ceiling. */
  score: number;
  /** Counted rather than summed, because `contentScore` is not linear. */
  contentHits: number;
  reasons: string[];
}

export async function locate(request: LocateRequest): Promise<LocateShortlist> {
  const limitations: string[] = [];
  const terms = normalizeTerms(request.terms, limitations);
  if (terms.length === 0) {
    return { terms: [], candidates: [], limitations: [...limitations, 'No usable search term was supplied.'] };
  }

  const projectRoot = normalizeRelative(request.project.root);
  const pathspec = projectRoot === '' ? null : literalPathspec(projectRoot);
  const files = (await request.git.listFiles(pathspec)).filter(
    (candidate) => inProject(projectRoot, candidate) && pathExclusionReason(candidate) === null,
  );
  if (files.length === 0) {
    return {
      terms,
      candidates: [],
      limitations: [...limitations, `Project "${request.project.id}" holds no reviewable files to search.`],
    };
  }

  const fileSet = new Set(files);
  const ranked = new Map<string, Ranked>();

  for (const term of terms) {
    const matchedPaths = pathMatches(term, files, limitations);
    const matchedContents = await contentMatches(request, term, pathspec, fileSet, limitations);

    const touched = new Set([
      ...matchedPaths.map((match) => match.path),
      ...matchedContents.map((match) => match.path),
    ]);
    if (isTooBroad(touched.size, files.length)) {
      limitations.push(
        `"${term}" matched ${touched.size} of the project's ${files.length} files, which is not a shortlist, so it was ignored.`,
      );
      continue;
    }
    if (touched.size === 0) {
      limitations.push(`No file's path or contents matched "${term}".`);
      continue;
    }

    for (const match of matchedPaths) {
      add(ranked, match.path, match.kind === 'directory' ? SCORE_DIRECTORY : SCORE_FILENAME, match.reason);
    }
    for (const match of matchedContents) {
      mention(ranked, match.path, match.reason);
    }
  }

  await addCoChange(request, ranked, fileSet, limitations);

  const ordered = [...ranked.values()]
    .map((entry) => ({ ...entry, score: entry.score + contentScore(entry.contentHits) }))
    .sort((a, b) => b.score - a.score || a.path.localeCompare(b.path));
  if (ordered.length > request.limit) {
    limitations.push(
      `${ordered.length - request.limit} further candidate(s) scored but are not listed; raise --limit to see them.`,
    );
  }

  return {
    terms,
    candidates: ordered.slice(0, request.limit).map((entry) => ({
      path: entry.path,
      // Two decimals: the co-change share is fractional, and a long float is
      // bytes spent on precision the ordering does not use.
      score: Math.round(entry.score * 100) / 100,
      reasons: entry.reasons,
    })),
    limitations,
  };
}

/**
 * The spellings one name is written in. A requirement says "Order/Refund", a
 * directory says `order-refund`, an identifier says `orderRefund`, a
 * constant says `ORDER_REFUND`: four conventions, one name. A search that knows only the
 * spelling the ticket happened to use finds only the prose — which is exactly
 * how a shortlist comes back holding nothing but translation files.
 *
 * Words are the letters-and-digits runs, split on separators and on camel
 * boundaries, lowercased. Every convention reduces to the same word list, so
 * the word list is what the forms below are built from.
 */
function wordsOf(term: string): string[] {
  return term
    .replace(/(\p{Ll}|\p{N})(\p{Lu})/gu, '$1 $2')
    .split(/[^\p{L}\p{N}]+/u)
    .filter((word) => word !== '')
    .map((word) => word.toLowerCase());
}

/**
 * Joining a term's words is another spelling of it only when the separator is
 * punctuation inside a name. Between digits the separator is arithmetic:
 * "250.5" joins to "2505", which matched `41.2505` inside SVG path coordinates
 * and put five illustration files in the top twenty of a real ticket's
 * shortlist. A term whose every word is digits therefore keeps only the one
 * spelling it was written in.
 */
function joinable(words: readonly string[]): boolean {
  return words.length > 1 && words.some((word) => !/^\p{N}+$/u.test(word));
}

/**
 * The path spellings to try, the term's own first so its reason is the one
 * reported when it matches. The joined forms hold only letters and digits, so
 * they are always safe to put in a glob — which also means a term carrying
 * glob syntax still contributes through them rather than being dropped.
 */
function pathForms(term: string): string[] {
  const words = wordsOf(term);
  const literal = term.toLowerCase();
  const forms = /^[^*?[\]{}()!\\]+$/.test(literal) ? [literal] : [];
  if (joinable(words)) forms.push(words.join('-'), words.join('_'), words.join(''));
  return [...new Set(forms)];
}

/**
 * The one extra content search worth a grep: every separator convention
 * collapses to the same letters and digits, so `refundlimit` finds
 * `refundLimit` and `REFUND_LIMIT` alike. Spellings only, never a second
 * term — two greps per term is the whole budget.
 */
function compactForm(term: string): string {
  const words = wordsOf(term);
  return joinable(words) ? words.join('') : term.toLowerCase();
}

/**
 * Where a lowercased spelling lands in a lowercased repository path: in a
 * directory above the file, in the filename, or nowhere. The answer is that
 * of `**\/*form*\/**` and then `**\/*form*`, including that a segment starting
 * with a dot anywhere in the path defeats both, but computed as substring
 * tests: `matchesGlob` compiles its pattern on every call. Measured on
 * inseer-frontend's 4,427 files and twelve spellings: 441 ms against 15 ms,
 * the same 520 hits, on every `locate` and `prepare`.
 * A literal spelling that holds `/` spans segments, and keeps the glob.
 */
export function pathHit(lowerPath: string, form: string): 'directory' | 'filename' | null {
  if (form.includes('/')) {
    if (matchesGlob(lowerPath, `**/*${form}*/**`)) return 'directory';
    return matchesGlob(lowerPath, `**/*${form}*`) ? 'filename' : null;
  }
  const segments = lowerPath.split('/');
  if (segments.some((segment) => segment.startsWith('.'))) return null;
  const last = segments.length - 1;
  for (let index = 0; index < last; index += 1) {
    if (segments[index]?.includes(form) === true) return 'directory';
  }
  return segments[last]?.includes(form) === true ? 'filename' : null;
}

/**
 * Signal 1 — path and filename. A filename hit is the weaker claim; a hit on
 * a directory above the file says a whole boundary was named. Both sides are
 * lowercased, and git reports POSIX paths on every platform, so a Windows
 * checkout compares the same strings a Linux one does.
 *
 * Each file takes its strongest single spelling: a directory hit on any form
 * beats a filename hit on any other, and no file is counted twice for being
 * written two ways.
 */
function pathMatches(
  term: string,
  files: readonly string[],
  limitations: string[],
): { path: string; kind: 'directory' | 'filename'; reason: string }[] {
  const forms = pathForms(term);
  if (forms.length === 0) {
    limitations.push(`"${term}" carries glob syntax, so it was matched against file contents only.`);
    return [];
  }

  const matches = new Map<string, { path: string; kind: 'directory' | 'filename'; reason: string }>();
  for (const form of forms) {
    const spelling =
      form === term.toLowerCase() ? `"${term}"` : `"${form}", a path spelling of "${term}"`;
    for (const file of files) {
      const hit = pathHit(file.toLowerCase(), form);
      if (hit === null) continue;
      const directory = hit === 'directory';
      if (matches.get(file)?.kind === 'directory') continue;
      matches.set(file, {
        path: file,
        kind: directory ? 'directory' : 'filename',
        reason: directory
          ? `sits under a directory matching ${spelling}`
          : `filename matched ${spelling}`,
      });
    }
  }
  return [...matches.values()];
}

/**
 * Signal 2 — contents, as a fixed case-insensitive string, bounded. The term
 * as written and its compact form are two spellings of one term, so a file
 * holding both is one mention, not two.
 */
async function contentMatches(
  request: LocateRequest,
  term: string,
  pathspec: string | null,
  fileSet: ReadonlySet<string>,
  limitations: string[],
): Promise<{ path: string; reason: string }[]> {
  const compact = compactForm(term);
  const spellings = [{ needle: term, reason: `contains "${term}"` }];
  if (compact !== term.toLowerCase() && compact.length >= MIN_TERM_LENGTH) {
    spellings.push({
      needle: compact,
      reason: `contains "${compact}", a compact spelling of "${term}"`,
    });
  }

  const matches = new Map<string, { path: string; reason: string }>();
  for (const spelling of spellings) {
    let found = (await request.git.grepFiles(spelling.needle, pathspec)).filter((path) =>
      fileSet.has(path),
    );
    if (found.length > MAX_CONTENT_MATCHES_PER_TERM) {
      limitations.push(
        `"${spelling.needle}" appears in ${found.length} files; only the first ${MAX_CONTENT_MATCHES_PER_TERM} were ranked.`,
      );
      found = found.slice(0, MAX_CONTENT_MATCHES_PER_TERM);
    }
    for (const path of found) {
      if (matches.has(path)) continue;
      matches.set(path, { path, reason: spelling.reason });
    }
  }
  return [...matches.values()];
}

/**
 * Signal 3 — co-change. This is the one that finds the *boundary* rather than
 * the keyword: the test file, the DTO, the migration, the route registration
 * that habitually moves with the files the terms already matched, and that
 * carry none of the terms themselves.
 *
 * Two git invocations, whatever the number of seeds: the commits that touched
 * any seed, then those commits' file lists. Nothing is kept between calls.
 */
async function addCoChange(
  request: LocateRequest,
  ranked: Map<string, Ranked>,
  fileSet: ReadonlySet<string>,
  limitations: string[],
): Promise<void> {
  const seeds = [...ranked.values()]
    .sort((a, b) => b.score - a.score || a.path.localeCompare(b.path))
    .slice(0, MAX_SEEDS)
    .map((entry) => entry.path);
  if (seeds.length === 0) return;

  const commits = await request.git.commitsTouching(seeds.map(literalPathspec), MAX_COCHANGE_COMMITS);
  if (commits.length < MIN_COCHANGE_COMMITS) {
    limitations.push(
      `Co-change contributed nothing: ${commits.length} commit(s) in this repository touch the files the terms matched.`,
    );
    return;
  }

  const lists = await request.git.commitFileLists(commits);
  const usable = lists.filter((entry) => entry.paths.length <= MAX_COCHANGE_COMMIT_FILES);
  if (usable.length < lists.length) {
    limitations.push(
      `${lists.length - usable.length} of ${lists.length} commit(s) changed more than ${MAX_COCHANGE_COMMIT_FILES} files and were not used for co-change.`,
    );
  }
  if (usable.length < MIN_COCHANGE_COMMITS) return;

  // The strongest single companionship, not the sum over every seed. Summing
  // would let a file that merely accompanies four seeds outrank the file the
  // terms actually named — which is what happened before this was capped, and
  // it is the difference between a shortlist and a list of neighbours.
  const best = new Map<string, { share: number; reason: string }>();
  const blocked: string[] = [];

  for (const seed of seeds) {
    const withSeed = usable.filter((entry) => entry.paths.includes(seed));
    if (withSeed.length < MIN_COCHANGE_COMMITS) continue;

    const counts = new Map<string, number>();
    for (const entry of withSeed) {
      for (const path of entry.paths) {
        if (path === seed || !fileSet.has(path)) continue;
        counts.set(path, (counts.get(path) ?? 0) + 1);
      }
    }

    const companions = [...counts]
      .filter(([, count]) => count >= MIN_COCHANGE_COUNT && count / withSeed.length >= MIN_COCHANGE_SHARE);
    if (companions.length > MAX_COCHANGE_PARTNERS) {
      blocked.push(`${seed} (${companions.length})`);
      continue;
    }

    for (const [path, count] of companions) {
      const share = count / withSeed.length;
      const existing = best.get(path);
      if (existing !== undefined && existing.share >= share) continue;
      best.set(path, {
        share,
        reason: `changed with ${seed} in ${count} of ${withSeed.length} commits`,
      });
    }
  }

  if (blocked.length > 0) {
    limitations.push(
      `Co-change contributed nothing for ${blocked.join(", ")}: each moves with more than ${MAX_COCHANGE_PARTNERS} other files, which is a set maintained as a block rather than a boundary.`,
    );
  }

  for (const [path, entry] of best) {
    add(ranked, path, SCORE_COCHANGE * entry.share, entry.reason);
  }
}

function add(ranked: Map<string, Ranked>, path: string, score: number, reason: string): void {
  entryFor(ranked, path).score += score;
  note(ranked, path, reason);
}

/** A mention is counted, not added: `contentScore` turns the count into a score. */
function mention(ranked: Map<string, Ranked>, path: string, reason: string): void {
  entryFor(ranked, path).contentHits += 1;
  note(ranked, path, reason);
}

function entryFor(ranked: Map<string, Ranked>, path: string): Ranked {
  const existing = ranked.get(path);
  if (existing !== undefined) return existing;
  const created: Ranked = { path, score: 0, contentHits: 0, reasons: [] };
  ranked.set(path, created);
  return created;
}

function note(ranked: Map<string, Ranked>, path: string, reason: string): void {
  const entry = entryFor(ranked, path);
  if (!entry.reasons.includes(reason)) entry.reasons.push(reason);
}

/**
 * A term that reaches most of the project is describing the project rather
 * than a boundary within it — `src`, the company name, the framework. Ignoring
 * it is the honest answer; ranking on it would return a list of everything
 * with the term's name on it, which is the failure this iteration exists to
 * avoid. The small absolute floor keeps a four-file project, where matching
 * three of them is perfectly informative, out of the rule.
 */
const TOO_BROAD_SHARE = 0.6;
const TOO_BROAD_MIN_FILES = 5;

function isTooBroad(matched: number, total: number): boolean {
  return matched >= TOO_BROAD_MIN_FILES && matched > total * TOO_BROAD_SHARE;
}

function inProject(projectRoot: string, repositoryRelativePath: string): boolean {
  if (projectRoot === '') return true;
  return repositoryRelativePath.startsWith(`${projectRoot}/`) || repositoryRelativePath === projectRoot;
}

function normalizeTerms(supplied: readonly string[], limitations: string[]): string[] {
  const seen = new Set<string>();
  const terms: string[] = [];
  const tooShort: string[] = [];

  for (const raw of supplied) {
    const term = raw.trim();
    if (term === '') continue;
    if (term.length < MIN_TERM_LENGTH) {
      tooShort.push(term);
      continue;
    }
    const key = term.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    terms.push(term);
  }

  if (tooShort.length > 0) {
    limitations.push(
      `Ignored term(s) shorter than ${MIN_TERM_LENGTH} characters: ${[...new Set(tooShort)].join(', ')}.`,
    );
  }
  if (terms.length > MAX_TERMS) {
    limitations.push(
      `Only the first ${MAX_TERMS} terms were searched; ${terms.length - MAX_TERMS} were dropped.`,
    );
    return terms.slice(0, MAX_TERMS);
  }
  return terms;
}

/**
 * Terms from retrieved requirement text, for a caller that has a ticket rather
 * than a list of words. This is a word-frequency heuristic and nothing more:
 * it is stated as one in the shortlist's limitations, and `--term` overrides
 * it whenever the caller knows better.
 *
 * Identifier-shaped tokens — `order_total`, `InvoiceService`, `src/orders` —
 * rank first, because a requirement that names code is naming the boundary.
 */
export function termsFromRequirements(
  sources: readonly Pick<RequirementSource, 'title' | 'content'>[],
): string[] {
  const found = new Map<string, { term: string; count: number; order: number; identifier: boolean }>();
  let order = 0;

  for (const source of sources) {
    for (const token of tokenize(`${source.title}\n${source.content}`)) {
      const key = token.toLowerCase();
      const existing = found.get(key);
      if (existing !== undefined) {
        existing.count += 1;
        continue;
      }
      found.set(key, { term: token, count: 1, order: (order += 1), identifier: isIdentifierLike(token) });
    }
  }

  return [...found.values()]
    .sort(
      (a, b) =>
        Number(b.identifier) - Number(a.identifier) || b.count - a.count || a.order - b.order,
    )
    .slice(0, MAX_TERMS)
    .map((entry) => entry.term);
}

function tokenize(text: string): string[] {
  const tokens: string[] = [];
  for (const raw of text.split(/[^\p{L}\p{N}_./-]+/u)) {
    const token = raw.replace(/^[./-]+/, '').replace(/[./-]+$/, '');
    if (token.length < MIN_TERM_LENGTH) continue;
    if (/^\p{N}+$/u.test(token)) continue;
    if (isIdentifierLike(token)) {
      tokens.push(token);
      continue;
    }
    if (token.length < 4 || STOPWORDS.has(token.toLowerCase())) continue;
    tokens.push(token);
  }
  return tokens;
}

/** `order_total`, `InvoiceService`, `src/orders`, `tax.rate` — but not `Order`. */
function isIdentifierLike(token: string): boolean {
  return /[_./-]/.test(token) || /\p{Ll}\p{Lu}/u.test(token);
}

/**
 * Words that appear in every requirement document ever written. A short,
 * deliberately unambitious list: the breadth guard above is what actually
 * stops a useless term, so this only avoids spending a grep on "should".
 */
const STOPWORDS = new Set([
  'about', 'after', 'also', 'always', 'another', 'because', 'been', 'before', 'being', 'both',
  'cannot', 'could', 'description', 'does', 'done', 'each', 'either', 'else', 'every', 'from',
  'given', 'have', 'here', 'however', 'into', 'issue', 'it’s', 'just', 'like', 'made', 'make',
  'many', 'more', 'most', 'must', 'need', 'needs', 'never', 'none', 'only', 'other', 'over',
  'page', 'part', 'please', 'rather', 'same', 'shall', 'should', 'since', 'some', 'stop', 'such',
  'summary', 'sure', 'than', 'that', 'their', 'them', 'then', 'there', 'these', 'they', 'this',
  'those', 'through', 'ticket', 'time', 'under', 'until', 'upon', 'used', 'user', 'using', 'very',
  'want', 'were', 'what', 'when', 'where', 'which', 'while', 'will', 'with', 'within', 'without',
  'work', 'would', 'your',
]);
